### ISSUE TITLE
Cannot upload any file over 90MB

### ISSUE THREAD

**Issue by BackedUpBooty** [ZizzyDizzyMC/linx-server#3]
HI there, 

I'm running this on docker on a Synology 920+. I've got this up and running with a reverse proxy `https://linx.mydomain.com` with the following docker-compose file:
```
services:
  linx-server:
    container_name: linx
    image: andreimarcu/linx-server
    command: -config /data/linx-server.conf
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - $DOCKERDIR/linx/files:/data/files
      - $DOCKERDIR/linx/meta:/data/meta
      - $DOCKERDIR/linx/linx-server.conf:/data/linx-server.conf
    networks:
      - Horus
    ports:
      - "8081:8080"
    restart: unless-stopped
```
and the following linx-server.conf
```
bind = 127.0.0.1:8080
sitename = myLinx
siteurl = https://linx.mydomain.com/
selifpath = s
maxsize = 4294967296
maxexpiry = 259200
allowhotlink = true
remoteuploads = true
nologs = true
force-random-filename = false
cleanup-every-minutes = 5
```

I can happily upload and access any file up to approx. 90MB, but anything over that just doesn't even start to upload (tracker on the right stays at 0%). The container logs don't actually show any info on this so I can't seem to track this down.

A separate issue - I tried to add another 2 arguments to the conf file, `max-duration-time = 3600` and `max-duration-size = 4294967296` but on restarting the container the logs had a recurring output of 'unknown flag name` for both. This issue is secondary to the above. 

Cheers!
