### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by geekedtv** [ZizzyDizzyMC/linx-server#5]
I've tried giving the folders permissions running the command in the instructions, tried adding PUID and PGID but always getting bad requests and permission denied no matter what I try even after restarting the container.

**Comment by ZizzyDizzyMC** [comment]
I've not yet been able to work on the docker implementation of linx-server.   I will assign myself this task to work on it in an upcoming update to linx-server.

**Comment by ccclxxiii** [comment]
@ZizzyDizzyMC @ItsNoted 

this is an old issue, but the problem stems from the dockerfile using `USER nobody` which is uid `65534`.  because it's bind-mounted  you'd have to execute `sudo chown -R 65534:65534 ./files ./meta` on the docker host.  probably not the best solution.  a different way to approach it without having to alter the dockerfile is to use named volumes as in this example below.

i was able to reproduce the permission issue and eliminate it moving to named volumes.

````
---
services:
  linx-server:
    container_name: linx-server
    image: andreimarcu/linx-server
    command: -config /data/linx-server.conf
    volumes:
      - linx_files:/data/files
      - linx_meta:/data/meta
      - linx_locks:/data/locks
      - ./linx-server.conf:/data/linx-server.conf  # config can be bind-mounted
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  linx_files:
  linx_meta:
  linx_locks:
````
